#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

-
  name: 'Blog post comment creation'
  uriPattern:    'robertlemke/plugin/blog/comments/create'
  defaults:
    '@package':    'RobertLemke.Plugin.Blog'
    '@controller': 'Comment'
    '@format': 'html'
    '@action': 'create'

# THE FOLLOWING ROUTES CURRENTLY DON'T WORK WITH CONTENT DIMENSIONS, WILL FIX THAT ASAP:

# http://example.dev/en/blog
# ?--typo3_neos_nodetypes_typoscript_pluginimplementation[@package]=RobertLemke.Plugin.Blog
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[@controller]=Post
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[@action]=index
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@package]=
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@subpackage]=
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@controller]=
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@action]=index
# &--typo3_neos_nodetypes_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][currentPage]=2

-
  name: 'Blog post pagination default'
  uriPattern:    '{node}'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--posts-paginator':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler:    'Neos\Neos\Routing\FrontendNodeRoutePartHandler'

-
  name: 'Blog post pagination - page > 1'
  uriPattern:    '{node}/page/{--posts-paginator.currentPage}'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--posts-paginator':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler:    'Neos\Neos\Routing\FrontendNodeRoutePartHandler'

-
  name:          'RSS Feed special super extra workaround route (for until we can use different formats in plugins)'
  uriPattern:    '{node}.xml'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'xml'
    '@action':     'show'
  routeParts:
    node:
      handler:    'Neos\Neos\Routing\FrontendNodeRoutePartHandler'
