#                                                                        #
# Default subroutes configuration for the Blog package                   #
#                                                                        #

-
  name: 'Blog post comment creation'
  uriPattern:    'robertlemke/plugin/blog/comments/create'
  defaults:
    '@package':    'RobertLemke.Plugin.Blog'
    '@controller': 'Comment'
    '@format': 'html'
    '@action': 'create'

# http://example.dev/en/blog
# ?--typo3_neos_typoscript_pluginimplementation[@package]=RobertLemke.Plugin.Blog
# &--typo3_neos_typoscript_pluginimplementation[@controller]=Post
# &--typo3_neos_typoscript_pluginimplementation[@action]=index
# &--typo3_neos_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@package]=
# &--typo3_neos_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@subpackage]=
# &--typo3_neos_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@controller]=
# &--typo3_neos_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][@action]=index
# &--typo3_neos_typoscript_pluginimplementation[--typo3-typo3cr-viewhelpers-widget-paginateviewhelper][currentPage]=2

-
  name: 'Blog post creation'
  uriPattern:    '{node}/post/create'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--typo3_neos_typoscript_pluginimplementation':
      '@package': 'RobertLemke.Plugin.Blog'
      '@controller': 'Post'
      '@action': 'create'
      '@format': 'html'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true

-
  name: 'Blog post pagination default'
  uriPattern:    '{node}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--typo3_neos_typoscript_pluginimplementation':
      '@package': 'RobertLemke.Plugin.Blog'
      '@controller': 'Post'
      '@action': 'index'
      '--posts-paginator':
        '@package': ''
        '@subpackage': ''
        '@controller': ''
        '@action': 'index'
        'currentPage': ''
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true

-
  name: 'Blog post pagination - page > 1'
  uriPattern:    '{node}/page/{--typo3_neos_typoscript_pluginimplementation.--posts-paginator.currentPage}'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--typo3_neos_typoscript_pluginimplementation':
      '@package': 'RobertLemke.Plugin.Blog'
      '@controller': 'Post'
      '@action': 'index'
      '--posts-paginator':
        '@package': ''
        '@subpackage': ''
        '@controller': ''
        '@action': 'index'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: true

-
  name:          'RSS Feed special super extra workaround route (for until we can use different formats in plugins)'
  uriPattern:    '{node}.xml'
  defaults:
    '@package':    'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'xml'
    '@action':     'show'
  routeParts:
    node:
      handler:    TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
