#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

RobertLemke:
  Plugin:
    Blog:
      notifications:
        to:
          email: ''
          name: 'Blog Admin'

      # this is deprecated and should be configured via TypoScript instead
      feed:
        title: 'The Neos Blog'
        description: 'A great, new - yet unconfigured - blog powered by Neos'
        uri: ''
        includeContent: false

Neos:
  Flow:
    object:
      excludeClasses:
        'simplepie.simplepie': ['.*']

  Neos:
    nodeTypes:
      groups:
        blog:
          position: 'after plugins'
          label: Blog
    fusion:
      autoInclude:
        RobertLemke.Plugin.Blog: true
