#                                                                        #
# Settings Configuration for the Blog package                            #
#                                                                        #

RobertLemke:
  Plugin:
    Blog:
      notifications:
        to:
          email: ''
          name: 'Blog Admin'

      feed:
        title: 'The TYPO3 Neos Blog'
        description: 'A great, new - yet unconfigured - blog powered by TYPO3 Neos'
        uri: ''
        includeContent: FALSE

TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'RobertLemke.Plugin.Blog': TRUE

    nodeTypes:
      groups:
        blog:
          position: 'after plugins'
          label: 'Blog'
  Flow:
    object:
      excludeClasses:
        'simplepie.simplepie': ['.*']
